AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/*.gemspec'
    - 'pkg/**/*'

Style/RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100
